# Generated by Django 2.2.28 on 2022-05-02 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0057_auto_20211214_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bim3DModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=400)),
                ('file', models.FileField(default='', help_text='only accept .xkt format for now see below', upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IfcClass',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('bimModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmi.Bim3DModel')),
                ('content', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hmi.WidgetContent')),
            ],
        ),
    ]
