# Generated by Django 2.2.28 on 2022-05-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0058_bim3dmodel_ifcclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ifcclass',
            name='bimModel',
        ),
        migrations.RemoveField(
            model_name='ifcclass',
            name='content',
        ),
        migrations.DeleteModel(
            name='Bim3DModel',
        ),
        migrations.DeleteModel(
            name='IfcClass',
        ),
    ]
